version: "3.7"

services:
    broker-ui-service:
        image: radheshyambaliga/mse-broker-ui-service
        container_name: mse-broker-ui-service
        restart: on-failure
        ports:
            - "3000:3000"
        tty: true
        stdin_open: true
        networks:
            - mse-network
            
networks:
    mse-network:
        external:
            name: mse-network