export const FETCH_ORDERS_START = "FETCH_ORDERS_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export const FETCH_EXECUTIONS_START = "FETCH_EXECUTIONS_START";
export const FETCH_EXECUTIONS_SUCCESS = "FETCH_EXECUTIONS_SUCCESS";
export const FETCH_EXECUTIONS_FAIL = "FETCH_EXECUTIONS_FAIL";

export const NEW_ORDER_REQUEST_START = "NEW_ORDER_REQUEST_START";
export const NEW_ORDER_REQUEST_SUCCESS = "NEW_ORDER_REQUEST_SUCCESS";
export const NEW_ORDER_REQUEST_FAIL = "NEW_ORDER_REQUEST_FAIL";
