version: "3.7"

services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        ports:
            - "2181:2181"
        networks:
            - mse-network
            
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        hostname: kafka
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            #KAFKA_ADVERTISED_HOST_NAME: kafka
            #KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        networks:
            - mse-network
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
networks:
    mse-network:
        external:
            name: mse-network